# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reviewreminder < Formula
  desc "Remind colleagues to review your code"
  homepage "https://github.com/evoteum/reviewreminder"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evoteum/reviewreminder/releases/download/v0.1.0/reviewreminder_0.1.0_darwin_amd64.tar.gz"
      sha256 "76fd87d32d92ea76361d7523857eba1563cad0a3fefea043cdec270045fa69ed"

      define_method(:install) do
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evoteum/reviewreminder/releases/download/v0.1.0/reviewreminder_0.1.0_darwin_arm64.tar.gz"
      sha256 "f77642a81e4945237baaf9c009a1b3efaffd9be584cf09567435d5966675b15f"

      define_method(:install) do
        bin.install "rr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evoteum/reviewreminder/releases/download/v0.1.0/reviewreminder_0.1.0_linux_amd64.tar.gz"
      sha256 "cdd4fafb326e97f34416208eace8659e7e8db3ef7d9969f1d21fa2c43f268dc1"
      define_method(:install) do
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evoteum/reviewreminder/releases/download/v0.1.0/reviewreminder_0.1.0_linux_arm64.tar.gz"
      sha256 "902517ca9a5b6780be561ce9b116ac00828551b5d1732a6bf2790b54b29b9117"
      define_method(:install) do
        bin.install "rr"
      end
    end
  end

  test do
    system "#{bin}/rr", "version"
  end
end
